cpan-api/Dockerfile
build image (cd cpan-api; docker build -t cpan-api .) failed, because missing some gmc.h library for module Crypt::DH::GMP (and this is dependency of module Net::OpenID::Common)
```
(...)
! Configure failed for Crypt-DH-GMP-0.00012. See /root/.cpanm/work/1423053241.7/build.log for details.
! Installing the dependencies failed: Module 'Crypt::DH::GMP' is not installed
! Bailing out the installation for Net-OpenID-Common-1.18.
Successfully installed JSON-2.90
! Installing the dependencies failed: Module 'Net::OpenID::Common' is not installed
! Bailing out the installation for Net-OpenID-Consumer-1.15.
(...)
! Installing the dependencies failed: Module 'Test::OpenID::Server' is not installed, Module 'Net::OpenID::Consumer' is not installed
! Bailing out the installation for /cpan-api/.
385 …
```
=> missing dependency of Crypt::DH::GMP

.env, docker-compose.localapi.yml, docker-compose.yml, localapi.env
Migrate from using environment variables within the docker compose files
into separate environment files that docker-compose loads/references.
This is a first step in migrating configuration details out of docker
compose files and into separate files that the users can edit.
=> Add environment files

configs/metacpan-api/metacpan_server.conf, docker-compose.localapi.yml, docker-compose.yml, pg/Dockerfile, pg/docker-entrypoint-initdb.d/100-roles.sql, pg/docker-entrypoint-initdb.d/200-minion.sql, pg/healthcheck.sh
Create a new PostgreSQL container and add configuration for minion to be able to use it. By default version 9.6 is installed, but that can be changed by the `PG_TAG` setting. 
Database data is persistently stored in the local `pgdb-data` directory and network communication is done via the `database` network.
One required change, is setting the `docker-compose` `version` parameter to `3.4` from `3`, this allows extended syntax for added clarity (further changes coming to use this syntax in other pull requests).
=> Add a PostgreSQL container

configs/metacpan-api/metacpan_server.conf, docker-compose.localapi.yml, pg/docker-entrypoint-initdb.d/100-roles.sql
When starting with a fresh build of the containers there were errors encountered. These changes are the fixes required to start a build from scratch.
=> Fixes Related to PostgreSQL Database Container

README.md
I guess this is basic Docker stuff, but I think it's helpful to have here.
=> Add instructions to README for peeking into a container

base/Dockerfile, base/cpanfile, base/cpanfile.snapshot, base/wait-for-it.sh
This is a base level image to be used in the creation of other metacpan images. This image collects the common base perl distributions.
=> Add metacpan-base image

base/Dockerfile
All the perl tools are installed in `/usr/local/bin`, copy it into the new image so that the tools are executable.
=> Add bin directory

docker-compose.yml
Use the official mongodb image even though it's xenial and not small
alpine. For some reason the alpine image kept network disconnecting
causing github-meets-cpan to go down.
=> Change mongodb image

docker-compose.yml
This will have docker check the health of the container using the simple
MongoDB ping command and checking for an `ok` status.
=> Add healthcheck option for mongodb

README.md
With all the work that's been done on getting the containers up and
running, time to update the documentation to reflect those changes.
There is more documentation changes to come, this however does get the
quick start handled, and should allow other people to run the
containers.
=> Update documentation to include docker-compose

README.md, docker-compose.yml
This merge request is to make the documentation for getting started clearer. Removes the requirement for the logspout container, and supplies a development configuration for the API to start.
=> Additional docker container and documentation clean ups

.env
Fixes #49
We do not need to restart the webapp every time there
is a log entry in var/log/metacpan.log otherwise
we will end up always restarting in development.
=> Do not refresh morbo app when log is updated

bin/metacpan-docker
bin/metacpan-docker when run from the command line
should try to run the default 'init' action.
=> Run init as default action for bin/metacpan-docker

.gitignore, bin/metacpan-docker
Fixes GH #53
This can clearly be improved but this is a starting point
and if you have any local change uncommited when doing
a reset it will abort as we are usign 'set -e' which
is a good thing
=> Basic update and reset methods to keep repo up to date

.travis.yml, README.md, bin/metacpan-docker, docker-compose.yml, grep.env
This is adding metacpan/metacpan-grep-front-end
to docker-compose using a local volume for git.
The volume 'metacpan_git_shared' could also be used
by other docker containers. In development we are
going to use a smaller & frozen version.
=> Add grep.metacpan development environment

README.md, docker-compose.yml
We can now use domain to access to each
individual services:
- http://api.metacpan.localhost
- http://web.metacpan.localhost
- http://gh.metacpan.localhost
- http://grep.metacpan.localhost
The dashboard is accessible there:
http://localhost:8080
=> Add traefik for common services

bin/metacpan-docker, docker-compose.yml
The definition of the metacpan_git_shared docker volume in the
docker-compose file is causing issues with deploying the image, as the
volume location has changed. By defining the volume to docker first and
then just using it in the docker-compose file, this problem is bypassed.
=> Automatically create docker volume with script

docker-compose.yml
Let's explicitely expose docker containers
using: traefik.enable=true
=> Do not expose docker containers by default

.github/workflows/up.yml, docker-compose.yml
Removing the api_test container, as tests should be executable from the api
container. In order to do so however, there needs to be 2 ES containers, one
for running and one for testing. To facilitate this removing the loccalhost
port binding definition for the ElasticSearch containers. Communication with
the containers is done over the elasticsearch network, and the host
communication is still available over the dynamically assigned port.
There was also an issue starting the postgres container because the image now
requires a password to be set for the postgres user. This issue is now fixed.
=> Fix container definitions

.github/workflows/up.yml, docker-compose.yml
The metacpan-api CI relies on this naming.
=> Revert apitest to api_test

configs/metacpan-api/metacpan_server.conf, pg/docker-entrypoint-initdb.d/100-roles.sql
In order to get `metacpan_api` working under Docker, a password needs to be set for the `metacpan` User.
This PR does both halves; sets a password in the DB setup, and then updates the config to use that password when Minion connects to the DB.
=> Fix PGDB authentication

configs/metacpan-web/metacpan_web.conf
Over time, the configuration for `metacpan_web` drifted from what can be found in the [metacpan/metacpan-web](https://github.com/metacpan/metacpan-web) repository.
This PR tries to help bring it back into line, so that the container can be started under Docker.
=> Fix metacpan_web config

bin/index-cpan.sh
Can't verify Permissions or check on the status of various Notifications without having the Permissions indexed, so make sure that we reindex Permissions when doing the initial setup of the partial CPAN index.
=> Re-index Permissions during initial setup.

.env, grep.env
Docker started throwing error messages because of the dashes (`-`) that
appear as part of of the environment variables being set. Adding double
quotes around the setting fixes the error.
=> Fix quoting setting environment variables

.circleci/config.yml, .env
For the development that will clear broken _ElasticSearch_ indices in development and testing environments as discussed at:
[Clear unknown Indices en Development](https://github.com/metacpan/metacpan-api/pull/1065)
the Automated Testing Environment needs to be adjusted accordingly.
* Blocks metacpan-api#1065
* Closes #93
=> Mark the Automated Testing Environment with MOJO_MODE

docker-compose.yml
This is adding an extra (unneeded) layer of complexity to the dev
environment. It's simpler to use ports than having to add hostnames to
your system config and also having to troubleshoot traefik.
=> Remove traefik

compose/web.yml, docker-compose.yml
Rather than having an entirely separate configuration for metacpan-web, include its docker-compose.yml file, but with some overrides.
=> include web docker-compose file

bin/partial-cpan-mirror.sh
One of the local operations commonly used for testing the API, performed by `bin/metacpan author`, requires the _find-ls.gz_ file, which was not included in the default partial CPAN. By adding this file to the loading script, testing becomes easier and eliminates the need for manual intervention to include the index.
=> Add missing index file on partial CPAN

compose/web.yml
Reverts metacpan/metacpan-docker#114
At this point we should be running `docker compose build` to create the development web container. It adds some build time up front, but after that it should be a better experience.
=> Revert "specify image name for web-server"

README.md, docker-compose.yml
Following the steps for initialization, I had to kickstart the web server before I was able to browse through port 5001. Apparently, the web server isn't automatically started.
=> Fix the order of instructions for initialization
